# CS109a FA18 Group 65 Final Project - Midterm Elections



## Data Preparation - American Community Survey Data - Congressional Districts

In [6]:
import csv
import pandas as pd
import numpy as np
import requests
from IPython.core.display import HTML
from IPython.display import display

### 2005-2017 data

In [22]:
# define paths

acs_data = "data/acs-1-year_tables_2005-2017"
variables_file = "vars_2005-2017.csv"
output_dir = "data/"
output_file = "acs-congressional_2005-2017.csv"

variables = pd.read_csv(acs_data + "/" + variables_file)

In [8]:
variables

,Topic,Table,Variable,Annotation
0,Race,B02001,HD01_VD01,Estimate; Total:
1,Race,B02001,HD01_VD02,Estimate; Total: - White alone
2,Race,B02001,HD01_VD03,Estimate; Total: - Black or African American a...
3,Race,B02001,HD01_VD04,Estimate; Total: - American Indian and Alaska ...
4,Race,B02001,HD01_VD05,Estimate; Total: - Asian alone
5,Race,B02001,HD01_VD06,Estimate; Total: - Native Hawaiian and Other P...
6,Race,B02001,HD01_VD07,Estimate; Total: - Some other race alone
7,Race,B02001,HD01_VD08,Estimate; Total: - Two or more races:
8,Citizenship,B05001,HD01_VD02,"Estimate; Total: - U.S. citizen, born in the U..."
9,Citizenship,B05001,HD01_VD03,"Estimate; Total: - U.S. citizen, born in Puert..."
10,Citizenship,B05001,HD01_VD04,"Estimate; Total: - U.S. citizen, born abroad o..."
11,Citizenship,B05001,HD01_VD05,Estimate; Total: - U.S. citizen by naturalization
12,Citizenship,B05001,HD01_VD06,Estimate; Total: - Not a U.S. citizen
13,Housing Costs,B25105,HD01_VD01,Estimate; Median monthly housing costs
14,Housing Costs,B25105,HD02_VD01,Margin of Error; Median monthly housing costs
15,Age and Sex,S0101,HC01_EST_VC37,Total; Estimate; SUMMARY INDICATORS - Median a...
16,Age and Sex,S0101,HC01_EST_VC38,Total; Estimate; SUMMARY INDICATORS - Sex rati...
17,Age and Sex,S0101,HC01_EST_VC39,Total; Estimate; SUMMARY INDICATORS - Age depe...
18,Age and Sex,S0101,HC01_EST_VC40,Total; Estimate; SUMMARY INDICATORS - Old-age ...
19,Age and Sex,S0101,HC01_EST_VC41,Total; Estimate; SUMMARY INDICATORS - Child de...
20,Age and Sex,S0101,HC02_EST_VC37,Percent; Estimate; SUMMARY INDICATORS - Median...
21,Age and Sex,S0101,HC02_EST_VC38,Percent; Estimate; SUMMARY INDICATORS - Sex ra...
22,Age and Sex,S0101,HC02_EST_VC39,Percent; Estimate; SUMMARY INDICATORS - Age de...
23,Age and Sex,S0101,HC02_EST_VC40,Percent; Estimate; SUMMARY INDICATORS - Old-ag...
24,Age and Sex,S0101,HC02_EST_VC41,Percent; Estimate; SUMMARY INDICATORS - Child ...
25,Age and Sex,S0101,HC03_EST_VC37,Male; Estimate; SUMMARY INDICATORS - Median ag...
26,Age and Sex,S0101,HC03_EST_VC38,Male; Estimate; SUMMARY INDICATORS - Sex ratio...
27,Age and Sex,S0101,HC03_EST_VC39,Male; Estimate; SUMMARY INDICATORS - Age depen...
28,Age and Sex,S0101,HC03_EST_VC40,Male; Estimate; SUMMARY INDICATORS - Old-age d...
29,Age and Sex,S0101,HC03_EST_VC41,Male; Estimate; SUMMARY INDICATORS - Child dep...
...,...,...,...,...
43,Age and Sex,S0101,HC06_EST_VC40,Percent Female; Estimate; SUMMARY INDICATORS -...
44,Age and Sex,S0101,HC06_EST_VC41,Percent Female; Estimate; SUMMARY INDICATORS -...
45,Educational,S0701,HC01_EST_VC39,Total; Estimate; MARITAL STATUS - Population 1...
46,Educational,S0701,HC01_EST_VC40,Total; Estimate; MARITAL STATUS - Population 1...
47,Educational,S0701,HC01_EST_VC41,Total; Estimate; MARITAL STATUS - Population 1...
48,Educational,S0701,HC01_EST_VC42,Total; Estimate; MARITAL STATUS - Population 1...
49,Educational,S0701,HC01_EST_VC43,Total; Estimate; MARITAL STATUS - Population 1...
50,Educational,S0701,HC01_EST_VC47,Total; Estimate; EDUCATIONAL ATTAINMENT - Popu...
51,Educational,S0701,HC01_EST_VC48,Total; Estimate; EDUCATIONAL ATTAINMENT - Popu...
52,Educational,S0701,HC01_EST_VC49,Total; Estimate; EDUCATIONAL ATTAINMENT - Popu...
53,Educational,S0701,HC01_EST_VC50,Total; Estimate; EDUCATIONAL ATTAINMENT - Popu...
54,Educational,S0701,HC01_EST_VC51,Total; Estimate; EDUCATIONAL ATTAINMENT - Popu...
55,Educational,S0701,HC01_EST_VC64,Total; Estimate; Median income (dollars)
56,Educational,S0701,HC01_EST_VC68,Total; Estimate; POVERTY STATUS IN THE PAST 12...
57,Educational,S0701,HC01_EST_VC69,Total; Estimate; POVERTY STATUS IN THE PAST 12...
58,Educational,S0701,HC01_EST_VC70,Total; Estimate; POVERTY STATUS IN THE PAST 12...
59,Educational,S0701,HC01_EST_VC74,Total; Estimate; HOUSING TENURE - Population 1...
60,Educational,S0701,HC01_EST_VC75,Total; Estimate; HOUSING TENURE - Population 1...
61,Educational,S0701,HC02_EST_VC01,Moved; within same county; Estimate; Populatio...
62,Educational,S0701,HC03_EST_VC01,"Moved; from different county, same state; Esti..."
63,Educational,S0701,HC04_EST_VC01,Moved; from different state; Estimate; Popula...
64,Educational,S0701,HC05_EST_VC01,Moved; from abroad; Estimate; Population 1 yea...
65,Language,S1601,HC03_EST_VC01,Percent of specified language speakers - Spea...
66,Language,S1601,HC04_EST_VC01,Percent of specified language speakers - Perc...
67,Language,S1601,HC05_EST_VC01,Percent of specified language speakers - Spea...
68,Language,S1601,HC06_EST_VC01,Percent of specified language speakers - Perc...
69,Employment,S2301,HC01_EST_VC01,Total; Estimate; Population 16 years and over
70,Employment,S2301,HC02_EST_VC01,Labor Force Participation Rate; Estimate; Popu...
71,Employment,S2301,HC03_EST_VC01,Employment/Population Ratio; Estimate; Populat...
72,Employment,S2301,HC04_EST_VC01,Unemployment rate; Estimate; Population 16 yea...

In [9]:
state_names_abbr = pd.read_csv(acs_data + "/state_abbreviations_correspondence_table.csv")

def get_state_abbr(state_name):
    name = state_names_abbr[state_names_abbr.state_name == state_name].state_abb.values
    if name.shape[0] == 0:
        return "NONE"
    return name[0]

In [10]:
# %load "acs-util.py"
def get_dist_id_2000(dist_name):
    try:
        print(dist_name)
        abbr, dist_no = dist_name.split(" Congressional District ")
    except:
        return "NONE"
    if dist_no == "(at Large)":
        dist_no = "1"
    return "{}_{}".format(abbr, dist_no)

def get_dist_id_2005(dist_name):
    dist_info, state_name = dist_name.split(", ")
    abbr = get_state_abbr(state_name)
    if abbr == 'NONE':
        return "NONE"
    try:
        blah, dist_no = dist_info.split("(at Large")
        dist_no = "1"
    except:
        dist_no, blah = dist_info.split(" (")
        blah, dist_no = dist_no.split("District ")
    return "{}_{}".format(abbr, dist_no)

def get_dist_id(dist_name, year="2018"):
    result = ""
    if int(year) < 2005:
        result = get_dist_id_2000(dist_name)
    else:
        result = get_dist_id_2005(dist_name)
    return result

def map_dist_id(dist_name_arr, year="2018"):
    if int(year) < 2005:
        dist_func = lambda dist_name : get_dist_id_2000(dist_name)
    else:
        dist_func = lambda dist_name : get_dist_id_2005(dist_name)
    result = list(map(dist_func, list(dist_name_arr)))
    return np.array(result)

def get_all_dist_ids():
    id_column_ = "GEO.id"
    location_column_ = "GEO.display-label"
    annotation_row_ = "Id"
    ids_source = pd.read_csv(table_filename("2016", "B02001"))
    ids_source = ids_source[ids_source[id_column_] != annotation_row_]
    dist_names = ids_source[location_column_].unique()
    dist_ids = map_dist_id(dist_names)
    return dist_ids[dist_ids != "NONE"]

In [11]:
dist_test = "Congressional District 6 (109th Congress), Colorado"
get_dist_id(dist_test)

'CO_6'

In [12]:
years = [str(y) for y in range(2005,2018)]
tables = variables.Table.unique()

id_column_ = "GEO.id"
location_column_ = "GEO.display-label"
annotation_row_ = "Id"

In [13]:
def codes_for_table(table_code):
    return variables[variables.Table == table_code].Variable.unique()

In [14]:
def table_filename(year, table_code):
    yy = year[2:4]
    return "{}/ACS_{}_1YR_{}_with_ann.csv".format(acs_data, yy, table_code)

def data_for_table(year, table_code):
    data_ = pd.read_csv(table_filename(year, table_code))

    cols_ = [location_column_] + list(codes_for_table(table_code))
    print(table_code, " : ", cols_)
    print(data_.columns.shape[0], data_.columns.difference(cols_).shape[0])
    df_data_ = data_[data_[id_column_] != annotation_row_]
    df_ann_ = data_[data_[id_column_] == annotation_row_]
    df_data_sel = df_data_[cols_]
    df_ann_sel = df_ann_[cols_]
    return df_data_sel, df_ann_sel

def gather_data_for_year(year):
    year_data = pd.DataFrame()
    year_ann = pd.DataFrame()
    started = False
    for tbl in tables:
        df_data_, df_ann_ = data_for_table(year, tbl)
        if (not started):
            year_data = year_data.append(df_data_[location_column_])
            year_ann = year_ann.append(df_ann_[location_column_])
            started = True
        cols_to_add = list(df_data_.columns.difference([location_column_]))
        for c in cols_to_add:
            cname = tbl + "." + c
            year_data[cname] = df_data_[c]
            year_ann[cname] = df_data_[c]
    year_data['year'] = np.ones(year_data.shape[0]) * year
    year_ann['year'] = np.ones(year_data.shape[0]) * year
    return year_data, year_ann

df_2005_ = gather_data_for_year("2005")

B02001  :  ['GEO.display-label', 'HD01_VD01', 'HD01_VD02', 'HD01_VD03', 'HD01_VD04', 'HD01_VD05', 'HD01_VD06', 'HD01_VD07', 'HD01_VD08']
23 14
B05001  :  ['GEO.display-label', 'HD01_VD02', 'HD01_VD03', 'HD01_VD04', 'HD01_VD05', 'HD01_VD06']
15 9
B25105  :  ['GEO.display-label', 'HD01_VD01', 'HD02_VD01']
5 2
S0101  :  ['GEO.display-label', 'HC01_EST_VC37', 'HC01_EST_VC38', 'HC01_EST_VC39', 'HC01_EST_VC40', 'HC01_EST_VC41', 'HC02_EST_VC37', 'HC02_EST_VC38', 'HC02_EST_VC39', 'HC02_EST_VC40', 'HC02_EST_VC41', 'HC03_EST_VC37', 'HC03_EST_VC38', 'HC03_EST_VC39', 'HC03_EST_VC40', 'HC03_EST_VC41', 'HC04_EST_VC37', 'HC04_EST_VC38', 'HC04_EST_VC39', 'HC04_EST_VC40', 'HC04_EST_VC41', 'HC05_EST_VC37', 'HC05_EST_VC38', 'HC05_EST_VC39', 'HC05_EST_VC40', 'HC05_EST_VC41', 'HC06_EST_VC37', 'HC06_EST_VC38', 'HC06_EST_VC39', 'HC06_EST_VC40', 'HC06_EST_VC41']
219 209

KeyError: "['HC01_EST_VC38' 'HC01_EST_VC41' 'HC02_EST_VC38' 'HC02_EST_VC41'\n 'HC03_EST_VC38' 'HC03_EST_VC41' 'HC04_EST_VC37' 'HC04_EST_VC38'\n 'HC04_EST_VC39' 'HC04_EST_VC40' 'HC04_EST_VC41' 'HC05_EST_VC37'\n 'HC05_EST_VC38' 'HC05_EST_VC39' 'HC05_EST_VC40' 'HC05_EST_VC41'\n 'HC06_EST_VC37' 'HC06_EST_VC38' 'HC06_EST_VC39' 'HC06_EST_VC40'\n 'HC06_EST_VC41'] not in index"

In [23]:
def unemployment_for_year(year):
    data_ = pd.read_csv(table_filename(year, "S2301"))
    unemp_col = ["HC04_EST_VC01"]
    df_data_ = data_[data_[id_column_] != annotation_row_]
    df_data_["dist_id"] = map_dist_id(df_data_[location_column_].values)
    df_data_["dist_name"] = df_data_[location_column_]
    df_data_["year"] = year
    df_data_["unemployment"] = df_data_[unemp_col]
    df_data_ = df_data_[df_data_["dist_id"] != "NONE"]
    cols_to_keep = ["dist_id", "dist_name", "year", "unemployment"]
    return df_data_[cols_to_keep]

df_all = None
for yyyy in years:
    df_year_ = unemployment_for_year(yyyy)
    if df_all is None:
        df_all = df_year_
    else:
        df_all = df_all.append(df_year_)

display(df_all.head())
df_all.to_csv(output_dir + "congressional_district_unemployment_2005-2017.csv")

/usr/share/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/usr/share/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/share/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/usr/share/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,dist_id,dist_name,year,unemployment
1,AL_1,"Congressional District 1 (109th Congress), Ala...",2005,6.3
2,AL_2,"Congressional District 2 (109th Congress), Ala...",2005,6.7
3,AL_3,"Congressional District 3 (109th Congress), Ala...",2005,8.8
4,AL_4,"Congressional District 4 (109th Congress), Ala...",2005,6.9
5,AL_5,"Congressional District 5 (109th Congress), Ala...",2005,7.0

In [18]:
years

['2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017']

In [ ]:
### 2000-2004 ACS comes in a different format